### PR TITLE
Enabled the player to choose when to quit

### LINKED ISSUE #14: 4b - Hangman-02
In your `hangman.py`, write a program to accept input from a user. The input should be a single letter. 

- If the letter is in the selected word, print out 'YES' and the index of the letter in the word.
- If the letter is not in the word or if more than one letter was entered, print out 'NO'.

For example, using the selected word 'CHICKEN'

- if 'K' is entered, the output should be 'YES 4' (we are using zero-based index so we count starting from 0, left to right).

Notes:

- If the input letter is found in more than one places in the word, print out for all places

### LINKED ISSUE #18: 5a - Hangman-03
Modify your code to keep accepting input until the user presses a special key and the program stops.

Notes:

- A loop is needed so that each time a user enters an input an receives an output, the user can repeat the process without having to re-run the application
- The user enters a special key to exit the game. Let this special key be an exclamation mark `!`.
- Ensure that on each try, you inform the user what key they need to press to exit the game.

### PR DESCRIPTION
**Pull request by emmanueltukpe**
Resolved #14

### CODE REVIEW

**Comment by emmanueltukpe** [comment]
Resolved #21

**Comment by jirevwe** [comment]
This it not in the code yet 
```Ensure that on each try, you inform the user what key they need to press to exit the game.```

**Review by jirevwe — CHANGES_REQUESTED** [review]

**Comment by emmanueltukpe** [comment]
Resolved #21

**Comment by jirevwe** [comment]
Don't create a new commit, amend the old one.

**Comment by jirevwe** [comment]
You can't resolve a PR, you ca only resolve issues. so typing `resolves #21` is wrong

**Pull request closed without merging**
