### PR TITLE
rearranged code by putting them into functions

### LINKED ISSUE #26: 6a - Hangman-06
Modify your existing code to use functions.

We can think of the current hangman code as consisting of 3 different parts:

- A part that randomly selects the target word to be guessed
- A part that initialises the dictionary containing the target letters (used to track what letter has been guessed)
- A part that handles the user's guesses and related logic.

**Create the following functions with the following specifications to cover the above three parts of the code respectively.**

1. A function to get the target word: This has no input and returns a string containing the word.
2. A function to initialise the letters in the dictionary: This takes in no input but returns the dictionary containing the letters in their default False states.
3. A function to process each turn, where all the guessing logic is carried out: This takes in a string containing the input provided by the user and performs the operations that processes the input. Nothing is returned by the function.

Notes:

- Be sure to use descriptive names and proper naming conventions when naming your functions.
- Modify your code as needed to make use of the function calls instead.

### PR DESCRIPTION
**Pull request by emmanueltukpe**
Resolved #26

### CODE REVIEW

**Comment by jirevwe** [comment]
Add another commit with the doc strings and we're good

**Comment by jirevwe** [comment]
Remove the lines
```python
print("Let's play hangman!")
print("\n")
```

**Comment by emmanueltukpe** [comment]
Resolved #27

**Comment by jirevwe** [comment]
Did you read the document in the issue? 
These are not doc strings they are comments. Amend the commit with proper doc strings

**Comment by jirevwe** [comment]
Doc strings are like this
```py
def add(a, b):
"""
This function add two numbers together
"""
return a + b
```

**Review by jirevwe — APPROVED** [review]

**Pull request merged**
